import Head from 'next/head'
import Homepage from "../components/Homepage"
import RingLoader from "react-spinners/RingLoader";
import { css } from "@emotion/react";
import React, {useState, useEffect} from 'react'


const override = css`
  display: flex;
  margin: 0 auto;
  border-color: red;
  position: absolute;

  top: 40%;
  left:0%;
  right:0%;
  bottom:0%;
  
  alifn-items: center;
  justify-content: center;
  
`;

export default function Home() {
  const [loading, setLoading] = useState(false);
  useEffect(()=>{
setLoading(true)
setTimeout(()=>{
setLoading(false)
}, 7000)
  },[])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        loading ?
        <RingLoader color={'#d8aaf8'} loading={loading} css={override} size={150} />               
        :
<Homepage/>
      }


      
    </>
  )
}
